language: node_js
node_js:
  - "8"
  - "10"

before_script:
  - npm install -g npm@latest
  - npm ci

  # install nodecg for types
  - cd ..
  - git clone https://github.com/nodecg/nodecg.git
  - cd nodecg
  - git checkout 0455036d73722e759a8674d3e9037725f867b62f

  # move bundle to correct place relative to nodecg
  - 'move %TRAVIS_BUILD_DIR% bundles\%TRAVIS_REPO_SLUG%'
  - cd bundles\%TRAVIS_REPO_SLUG%

script:
  - npm run static
  - npm run build